.TH scaffold 1 scaffold\-0.0.1
.SH NAME
scaffold \- turn a one-off script into a project
.SH SYNOPSIS
.B scaffold SCRIPT [SCRIPT...]
.SH DESCRIPTION
.B scaffold
creates a directory for one or more new scripts to live in,
with simple default Makefiles and the beginnings of a man page.

.SH OPTIONS
none
.SH EXAMPLES
scaffold newscript
.SH FILES
.B /usr/local/etc/scaffold/_Makefile_
The Makefile template
.br
.B /usr/local/etc/scaffold/_man_
The man page template
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
