#!/bin/sh

# produce a directory for a new script to live in,
# with a nice default Makefile and scraps of a man page.
ETC='/usr/local/etc/scaffold'

for i in "$@"; do
    mv $i $i.bak
    mkdir $i
    mv $i.bak $i/$i
    sed 's/__FILE__/'$i'/g' "$ETC/Makefile.template"  >$i/Makefile
    sed 's/__FILE__/'$i'/g; s/__YEAR__/'$(date '+%Y')'/g' "$ETC/manpage.template" >$i/$i.1
done
